### ISSUE TITLE
BUG snapshotTime timezone. 

### ISSUE THREAD

**Issue by txu2014** [Dave-Vallance/bt-ig-store#4]
snapshotTime in historical price uses local timezone ('Europe/London'), while streaming data UTM are using UTC data.  We should convert them to the same timezone,  otherwise the snapshotTime show later than UTM, which causing 1 hour delay to LIVE mode. 
Alternatively, we can use  snapshotTimeUTC, which is a new field in IG rest v3 api.

**Comment by ghost** [comment]
seems like this project is dead? @Dave-Vallance

**Comment by txu2014** [comment]
PR added, pending merge.

**Comment by Dave-Vallance** [comment]
> seems like this project is dead? @Dave-Vallance

I don't have the time to actively develop it at the moment. It is something I might look at again in the future. However, I am happy to accept PR's in the meantime 

PR was merged - so will close this

**Comment by ghost** [comment]
Hi @Dave-Vallance Thank you for the project insights. I will submit a few PR's in coming weeks and months :)
